### ISSUE TITLE
The code can not be built

### ISSUE THREAD

**Issue by luongvo** [HossamOnsy/NimbleTask#2]
Hi @HossamOnsy , I'm `Lucas` from `Nimble`. I will review your assignment here by opening issue ticket. Please feel free to catch up on this and help us know more about you by discussing and resolving the issues.

Firstly, **I can not build this project** because lack of `activity_login`, please try to rebuild and update this project asap :)

**Comment by luongvo** [comment]
Seems `LoginActivity` is redundant, not being used by any components

**Comment by HossamOnsy** [comment]
LoginActivity doesn't exist on master or on Dev
