### ISSUE TITLE
Not well-structured with lot of redundant samples, test and commented codes

### ISSUE THREAD

**Issue by luongvo** [HossamOnsy/NimbleTask#4]
Well, we're relying on this assignment to evaluate your skill and knowledge about Android development. So at least in development, you should give better **well-structured project with clean-code, no unused/redundant comments or test codes**. To be honest, I saw a lot of sample things just made for testing should not be in final submission. Could you please try to re-check your project 1 more time to show us your best. Thanks.

https://github.com/HossamOnsy/NimbleTask/blob/72b016c266c9859185abc168933299e8c5a721fe/app/src/main/java/com/sam/nimbletask/repository/SurveysRepository.kt#L30
https://github.com/HossamOnsy/NimbleTask/blob/72b016c266c9859185abc168933299e8c5a721fe/app/src/main/java/com/sam/nimbletask/network/RestApi.kt#L15
https://github.com/HossamOnsy/NimbleTask/blob/72b016c266c9859185abc168933299e8c5a721fe/app/src/main/java/com/sam/nimbletask/models/AccessTokenResponseModel.kt#L19
https://github.com/HossamOnsy/NimbleTask/blob/363023a6af5624060cc99c227e69a055d6be2860/app/src/main/java/com/sam/nimbletask/utils/Utils.kt
https://github.com/HossamOnsy/NimbleTask/blob/72b016c266c9859185abc168933299e8c5a721fe/app/src/main/java/com/sam/nimbletask/viewmodels/SurveriesViewModel.kt#L62
https://github.com/HossamOnsy/NimbleTask/blob/master/app/src/main/res/layout/survey_item.xml#L81

**Comment by luongvo** [comment]
@HossamOnsy please take the time to resolve these issues here for re-evaluation, try to follow git-flow to resolve the issues by opening pull requests

**Comment by HossamOnsy** [comment]
Done , confirm to close the issue :D
