### ISSUE TITLE
Some issues in dependency injection

### ISSUE THREAD

**Issue by luongvo** [HossamOnsy/NimbleTask#6]
- `SurveysRepository` in `SurveriesViewModel` could be initialized by `SurveriesViewModel`'s constructor (and of course a factory is needed) instead of manually injecting https://github.com/HossamOnsy/NimbleTask/blob/72b016c266c9859185abc168933299e8c5a721fe/app/src/main/java/com/sam/nimbletask/viewmodels/SurveriesViewModel.kt#L32
- Any reason why do you use `@Reusable` instead of `@Singleton`?
- Why do we need `@JvmStatic` annotation in dagger modules?

**Comment by HossamOnsy** [comment]
altered 
@Reusable & @JvmStatic was a combination that fixed an issue in @Singleton in kotlin that wasn't resolved however now i altered the code to be Singleton as per the guides of Dagger and that issue 
Confirm to close the issue :D
